/**:
  ros__parameters:
    motor_inverted: false
    max_fwd_current: 100
    max_rev_current: 50
    max_fwd_rpm: 30000
    max_rev_rpm: 20000
    max_left_steering: 0.0
    max_right_steering: 1.0
    neutral_steering: 0.5

    js_steering_flipped: true
    js_throttle_flipped: false
    js_steering_axis: 0
    js_throttle_axis: 4
    js_mode_button: 8
    js_estop_button: 0

    port: "/dev/ttyACM0"
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 100.0
    current_min: -50.0
    duty_cycle_max: 0.0
    duty_cycle_min: 0.0
    position_max: 0.0
    position_min: 0.0
    servo_max: 1.0
    servo_min: 0.0
    speed_max: 23250.0
    speed_min: -23250.0
